name = "workers-visitors"
main = "src/index.ts"
compatibility_date = "2023-01-03"

kv_namespaces = [
    { binding = "DB", id = "df3f25720b7d41d7b347eebc4391b34b", preview_id = "38b0f0ee251d43a28405f21695d81cc5" }
]